[package]
name = "notnow"
version = "0.2.3"
edition = "2018"
authors = ["Daniel Mueller <deso@posteo.net>"]
license = "GPL-3.0-or-later"
homepage = "https://github.com/d-e-s-o/notnow"
repository = "https://github.com/d-e-s-o/notnow.git"
readme = "README.md"
categories = ["command-line-utilities", "text-editors"]
keywords = ["TODO", "tasks", "planner"]
description = """
A terminal based task and TODO management software.
"""

[badges]
gitlab = { repository = "d-e-s-o/notnow", branch = "master" }

[profile.release]
opt-level = "z"
debug = true
lto = true
codegen-units = 1
incremental = false

[features]
default = []
coredump = ["cdump"]
readline = ["rline"]

[dependencies.cell]
version = "0.1"

[dependencies.cdump]
version = "0.1"
package = "coredump"
optional = true

[dependencies.dirs]
version = "2.0"

[dependencies.gui]
version = "=0.6.0-alpha.0"
features = ["derive"]

[dependencies.libc]
version = "0.2"

[dependencies.rline]
version = "0.3"
optional = true

[dependencies.serde]
version = "1.0"
features = ["derive"]

[dependencies.serde_json]
version = "1.0"

[dependencies.termion]
version = "1.5"

[dependencies.uid]
version = "0.1"
